### ISSUE TITLE
Error Building hunter "CondaEnvironmentNotFoundError"

### ISSUE THREAD

**Issue by jeff-censec** [ThreatHuntingProject/hunter#3]
I was unable to build a fresh hunter image. I failed on the following line:
`RUN conda install -y --name python2 plotly`

With the following error:
```
Error trying to build new environment:
Removing intermediate container 267c9a09fa5e
Step 8 : RUN conda install -y --name python2 plotly
 ---> Running in 85eb9cab9e1a

CondaEnvironmentNotFoundError: Could not find environment: python2 .
You can list all discoverable environments with `conda info --envs`.

The command '/bin/sh -c conda install -y --name python2 plotly' returned a non-zero code: 1
Makefile:15: recipe for target 'build' failed
make: *** [build] Error 1
```
I added the following before and running the make continued successfully:
`RUN conda create -n python2 python=2.7`

I don't know if this will affect the image as I am building it for the first time to try it out.

I also had additional errors with the following RUN command:
`RUN pip2 install splunk-sdk`

I was able to correct this by installing and updating pip earlier in the Dockerfile. Below this line:
`RUN apt-get update --yes && apt-get clean`
I added these lines:
```
RUN apt-get install --yes python-pip
RUN pip install --upgrade pip
```

**Comment by HSIS007** [comment]
I am also getting the same error , is your issue resolved and how ?

**Comment by DavidJBianco** [comment]
It turns out that the upstream image (jupyter/pyspark-notebook:latest) stopped including support for the Python2 kernel by default.  I added it back, and made the necessary updates to install the basic analysis modules in the python2 environment.  I updated the repo, and the new image is pushing to Docker Hub now, too.  Thanks to both of you for pointing this out!
